spring.application.name=A41_2024427_biblioteca
server.port=8082

#persistenia / JPA / Conexion / PoolDeCoexion
datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/DBBiblioteca
spring.datasource.username=quintom
spring.datasource.password=admin
##hibernate
spring.jpa.hibernate.ddl-auto=none
Spring.jpa.show-sql=true
#Desactivar el tomcat
#Spring.main.web-application-type=none
joinfaces.primefaces.theme=vela